networks:
  caddy_net:
    external: true
  navidrome_internal_net:
    external: true
    
services:
  caddy-navidrome:
    image: caddy:2
    container_name: caddy-navidrome
    restart: unless-stopped
    volumes:
      - ./caddy_root:/usr/share/caddy
      - ./caddy_certs:/data/caddy/pki/authorities/local
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
      - navidrome_internal_net

volumes:
  caddy_data:
  caddy_config: