networks:
  navidrome_internal_net:
    external: true
    
services:
  registration:
    build: ./registration
    container_name: navidrome-registration
    restart: unless-stopped
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ND_API_URL: http://navidrome:4533/rest
      DB_PATH: /data/navidrome.db  # Path to database inside container
    volumes:
      - "${DOCKER_DATA_PATH:-./docker/data}:/data"      # Mount database volume
    networks:
      - navidrome_internal_net

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: ${ND_SCANSCHEDULE:-1h}
      ND_LOGLEVEL: ${ND_LOGLEVEL:-info}
      ND_ENABLEEXTERNALSERVICES: ${ND_ENABLEEXTERNALSERVICES:-"false"}
      ND_ENABLEDOWNLOADS: ${ND_ENABLEDOWNLOADS:-true}
      ND_ENABLESHARING: ${ND_ENABLESHARING:-true}
      ND_BASEURL: "https://${MUSIC_SERVER_ADDRESS:-}"  # Base URL for Caddy reverse proxy
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
    volumes:
      - "${DOCKER_DATA_PATH:-./docker/data}:/data"
      - "${MUSIC_DATA_PATH:-./music}:/music:ro"
    networks:
      - navidrome_internal_net