networks:
  caddy_net:
    external: true
  navidrome_internal_net:
    external: true
    
services:
  caddy-navidrome:
    image: caddy:2
    restart: unless-stopped
    container_name: ${CADDY_CONTAINER_NAME:-caddy-navidrome}
    environment:
      - NAVIDROME=${NAVIDROME_CONTAINER_NAME:-navidrome}
      - REGISTRATION=${REGISTRATION_CONTAINER_NAME:-registration}
    ports:
      - "${MUSIC_PORT:-80}:80"
    volumes:
      - ./caddy_root:/usr/share/caddy
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
      - navidrome_internal_net

volumes:
  caddy_data:
  caddy_config: